### ISSUE TITLE
Use native `framebuf` capabilities

### ISSUE THREAD

**Issue by ace-dent** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#76]
From [Discord](https://discord.com/channels/898292107289190461/898292174410612787/1073711549895692339), @demodude4u found micropython has a native frame buffer class and supports drawing primitives:
https://docs.micropython.org/en/latest/library/framebuf.html

This may be a useful replacement (/supplement) for some of the existing graphics API.

**Comment by jmtinycircuits** [comment]
We used that library in the initial stages of Thumby but ended up implementing our API. We went with our own implementation because we wanted users to be able to see the code in the Code Editor (although viper ended up making it hard to read), change it without re-compiling MicroPython, and allow us to make updates to the API without a new MicroPython firmware image.

Right now we are able to use vanilla MicroPython, we never build it.

Feel free to add something to the Thumby docs about framebuf if you can find a nice place to put it: [https://github.com/TinyCircuits/Thumby-Website](https://github.com/TinyCircuits/Thumby-Website)
